tweets/config/routes.rb
Tweets::Application.routes.draw do
 
resources :users do
  get 'timeline', on: :member
  get 'followers',  on: :member
  get 'followees',  on: :member

end
post 'change_privacy', to: 'users#change_privacy'
post 'retweet' ,to: 'posts#retweet'
get 'auto-complete', to: 'users#autocomplete_suggestions', as: :autocomplete

devise_for :user, controllers: {
  omniauth_callbacks: "omni_auth/omniauth_callbacks", 
  registrations: "omni_auth/registrations",
  sessions: "omni_auth/sessions"
}
resources :followings, only:[ :create, :destroy]
resources :posts, only: [:create, :index, :edit] do
  get 'hash_tags', on: :collection
  get 'user_tags', on: :collection
end
root 'posts#index'

  

end

tweets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweets</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true%>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
 
  <% #FIXME_AB: Why I am not allowed to see public timeline if I am not logged in? #fixed-%>
    <div class ="navigation_tabs">
      <%= link_to "Home", posts_path  %>
      <% if current_user %>
        <%= link_to "My Profile", user_path(current_user) %>
        <%= link_to "TimeLine", timeline_user_path(current_user) %>
        <%= link_to "Know each other", users_path %>
        <%= link_to "Mentions", user_tags_posts_path %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <%else%>
        <%= link_to "Login", new_user_session_path %>
      <%end%>
    </div>
    <%= render 'shared/notice' %>
    <%= yield %>
  </body>
</html>