quizapp/config/routes.rb
Quizapp::Application.routes.draw do

  resources :quizzes, only:[:show, :index]
  resources :user_answers, only: [:new, :index, :create]
  get 'result/:id', to: 'quizzes#result', as: :result

  namespace :admin  do
    resources :questions, only: [:index, :new, :show, :create]
    resources :quizzes, only: [:index, :new, :show, :create]
    resources :users, only: [:index]
  end

devise_for :user, controllers: {
  omniauth_callbacks: "omni_auth/omniauth_callbacks", 
  registrations: "omni_auth/registrations",
  sessions: "omni_auth/sessions"
}

root 'quizzes#index'

  

end

quizapp/app/models/question.rb
class Question < ActiveRecord::Base
  
  validates :question_type, presence: true
  validates :description, presence: true, :length => { :maximum => 160 }
  validates :description, uniqueness: true
  validate :answer_presence
  validate :choice_presence, on: :create
  has_many :tests
  has_many :quizzes, through: :tests
  has_many :choices
  has_many :user_answers

  accepts_nested_attributes_for :choices
  scope :by_type, ->(type) { where(question_type: type) }
  
  def answer_presence
    if choices.present? && correct_choices.length < 1
      errors.add :base, "Please select an answer.You cant leave it empty"
    end
  end

  def correct_choices
    choices.select { |choice| choice.correct == true }
  end


  def choice_presence
    if !choices.present?
      errors.add :base, "You cant create an empty question"
    end

  end

end

quizapp/app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::AdminBaseController
  before_action :set_question, only: [:show]

 
  def index
    if params[:question_type]
      @questions = Question.includes(:choices).by_type(params[:question_type])
    else
      @questions = Question.includes(:choices)
    end
  end

  def show
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    respond_to do |format|
      if @question.save
        flash[:notice] = 'Question was successfully created.'
        format.js { render js: %(window.location.href='#{admin_question_path(@question)}')}
      else
        format.js {render "shared/_error_messages", locals: { :target => @question } }
      end
    end
  end


  private
    def set_question
      @question = Question.find(params[:id])
      if @question.nil?
        flash[:alert] = "Question could not be found"
        redirect_to_back_or_default_url
      end
    end

    def question_params
      params.require(:question).permit(:question_type, :description, choices_attributes: [:content, :id, :correct])
    end
end

quizapp/app/views/admin/questions/_boolean_choice.html.erb
<% value = (@counter.odd?) ?  'True' : "False" %>
<div class="choices">
  <%= label_tag :content, value %> 
  <%= f.hidden_field :content, :value => value %> 
  <%= f.radio_button :correct, true, :class => "checked" %>
</div>

quizapp/app/views/admin/questions/_choice.html.erb
<div class="choices">

  <%=  f.label :content, @counter.to_s %>
  <%= f.text_field :content %> 
  <%= f.radio_button :correct, true, :class => "checked"%>
</div>

quizapp/app/views/admin/questions/_form.html.erb
<div class="error_messages">
</div>
<%= render "shared/error_messages", :target => @question if @question.errors.present? %>
  <div class ="question_create">
  <div class="question">
    <div class="heading">GENERATE QUESTION </div>
    <%= form_for [:admin, @question], :html => {:class => 'quiz_form' }, :remote => true do |f| %>
      <div class ="question_type">
        TYPE:
        <%= f.select :question_type, options_for_select(QUESTION_TYPE, :selected => params[:question_type]), prompt: "Select a type" %>
      </div>
      <div class="choice_list">
        CHOICES:
        <%= select_tag :no_of_choices, options_for_select(get_number_of_questions, :selected => params[:selectbox]),{:disabled => params[:question_type] == 'Analytical', data: { path: new_admin_question_path }}%>
      </div>
      <div class ="content" >
        <%= f.label :description, "Enter your Question" %><br>
        <%= f.text_area :description, :rows => 5, :cols => 60, :value => params[:content] %>
      </div>
      <div class ="nested_fields" >
        <%= add_nested_fields(params[:selectbox].to_i || 0, f.object, f, :choices)  if params[:question_type] == 'Single-Choice'%>
      </div>
      <div class ="boolean" >
        <%= add_boolean_nested_fields(2, f.object, f, :choices) if params[:question_type] == 'Analytical' %>
      </div>
      <div class="actions create_question quiz_submit">
        <div>
          <%= f.submit %>
          <span class="user_delete"><%= link_to "Cancel", admin_questions_path %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

quizapp/app/views/admin/questions/index.html.erb
<% @questions.each do |question| %>
  <div class = "tests">
    <%= "[" + question.question_type + "]" %>
    <span class = "show", data-name = '<%=question.id%>'><%= link_to "Question " + question.id.to_s , admin_question_path(id: question.id) %></span>
     <div class="question_text hidden", data-id= '<%= question.id%>'>
      <%= render :template => 'admin/questions/show', locals: {:@question => question} %>
    </div>
  </div>
<%end%>

quizapp/app/views/admin/questions/new.html.erb
<%= render 'form' %>

quizapp/app/views/admin/questions/show.html.erb
<% if @question.present? %>
<div class = "question">
  <div class="heading"></div>
  <div class = "question_content">
    Q. <%=@count.presence || @question.id %>
    <%= @question.description %>?
  </div>
  <div>
    <% @question.choices.each do |choice| %>

      <div class="answer_choices">
        <%= radio_button_tag '[user_answer][choice][' + choice.id.to_s + '][_destroy]', "", check_user_type(params, choice), :disabled => check_user_type(params, ""), :class => 'checked' %>
        <%= choice.content %>  
      </div>
    <%end%>
  </div>
</div>
<%end%>