STIapp/config/routes.rb
STIapp::Application.routes.draw do

  resources :comments

  resources :devices do
    resources :comments
  end
  resources :networks,:controller => :devices do
  resources :comments
  end#,:has_many => :comments
  resources :printings,:controller => :devices do
  resources :comments
  end#,:has_many => :comments

  

end

STIapp/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable ,polymorphic: true
end

STIapp/app/models/device.rb
class Device < ActiveRecord::Base
  has_many :comments ,  as: :commentable
  validates :name, :type, presence: true
end

STIapp/app/models/network.rb
class Network < Device
  #has_many :comments ,  as: :commentable
  validate  :at_least_one_checked
  def at_least_one_checked
  	if ethernet.blank? && wifi.blank?
  		errors.add(:network, "You must select at least one option.")
  	end
  end
end

STIapp/app/models/printing.rb
class Printing < Device
  #has_many :comments ,  as: :commentable
	validate  :at_least_one_checked

	def at_least_one_checked
		if inkjet.blank? && laser.blank?
			errors.add(:printing, "You must select at least one option.")
		end
	end
end

STIapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

STIapp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @commentable = find_commentable
    @comments = @commentable.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
     @commentable = find_commentable
    @comment = @commentable.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
def find_commentable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return $1.classify.constantize.find(value)
        end
      end
      nil
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:description)
    end

    
end

STIapp/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new

  end

  # def confirmation
    

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    # if ! params[:device][:type].blank?
    #   @device = Object.const_get(params[:device][:type]).new(device_params)
    # else
      @device =Device.new(device_params)
    # end
    respond_to do |format|
      if @device.save #&& @subclass.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        #@device =Device.new(device_params)
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
     # params[:device] 

     params.require(:device).permit(:name,:type,:laser,:ethernet,:wifi,:inkjet)
    end
end

STIapp/app/helpers/application_helper.rb
module ApplicationHelper
end

STIapp/app/helpers/comments_helper.rb
module CommentsHelper
end

STIapp/app/helpers/devices_helper.rb
module DevicesHelper
end

STIapp/app/views/devices/_form.html.erb
<%= form_for(@device, as: :device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.select :type , ["Network" ,"Printing"] ,prompt: "select a type" %>
  </div>
 <!--  <%if !f.object.type.blank? %>
    <%#= render :partial => "edit_" + f.object.type.downcase, :locals=>{:f=>f} %>
    <%end%> -->
  <div class="field Network hidden">
    <%= f.label :ethernet %><br>
    <%= f.check_box :ethernet,:class => "abc"%>
  </div>
  <div class="field Network hidden">
    <%= f.label :wifi %><br>
    <%= f.check_box :wifi ,:class => "abc"%>
  </div>
   <div class="hidden Printing field">
    <%#= label_tag "type" %><br />
    <%= f.label :laser, "laser"  %>
    <%= f.radio_button :laser, true ,:class=> "abc"%>
    <%#= f.label :laser, "inkjet", :value => "false" %>
    <%#= f.radio_button :laser, false %>
  </div>
 <div class="field hidden Printing">
    <%#= label_tag "type" %><br />
    <%= f.label :inkjet, "inkjet"  %>
    <%= f.radio_button :inkjet, true ,:class => "abc"%>
    <%#= f.label :laser, "inkjet", :value => "false" %>
    <%#= f.radio_button :laser, false %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

STIapp/app/views/devices/confirmation.html.erb
<%= current_user.name %>,
<%#= session["_voucherApp_session"] = nil %>


you have not done any activity in last one hour.kindly login again to continue
<% current_user = nil %>
<%= link_to "click here" , destroy_user_session_path , method: :delete%>

STIapp/app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

STIapp/app/views/devices/index.html.erb
<%#= request.original_url %>
<%#= request.fullpath %>
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%#= link_to 'Show', device %></td>
        <td><%#= link_to 'Edit', edit_device_path(device) %></td>
        <td><%#= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

STIapp/app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

STIapp/app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>type:</strong>
  <%= @device.type %>
</p>


<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>